//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADOR
    {
        public int ID { get; set; }
        public string MARCA { get; set; }
        public string SUBMARCA { get; set; }
        public string TIPO { get; set; }
        public string MODELO { get; set; }
        public string DESCRIPCION { get; set; }
        public string CODIGO_POSTAL { get; set; }
        public string ESTADO { get; set; }
        public string MUNICIPIO { get; set; }
        public string COLONIA { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string GENERO { get; set; }
    }
}
