//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOMOVIL
    {
        public int ID { get; set; }
        public string MARCA { get; set; }
        public string SUBMARCA { get; set; }
        public string TIPO { get; set; }
        public string MODELO { get; set; }
        public string DISCRIPCION { get; set; }
    }
}
